#!/bin/sh
Encoding=UTF-8

dists=$(cut -d: -f1 '/opt/penmode/modules/repository/settings/dists.txt')
archs=$(cut -d: -f1 '/opt/penmode/modules/repository/settings/archs.txt')
components=$(cut -d: -f1 '/opt/penmode/modules/repository/settings/components.txt')
pathrepo=$(cut -d: -f1 '/opt/penmode/modules/repository/settings/path.txt')
repo=$(cut -d: -f1 '/opt/penmode/modules/repository/settings/repo.txt')
export MAIN_DIALOG='
<window window_position="1" title="Repository" image-name="/opt/penmode/icons/icon.png">
        <vbox>
        <frame>
        <hbox>
       <text>
				<label>DISTS :</label>
			</text>
        <entry>
			<default>'$dists'</default>
			<variable>default_dists</variable>
		</entry>
		
		  <button>
        <input file>/opt/penmode/modules/repository/icons/save.png</input>
		<width>30</width>
          <action>/opt/penmode/modules/repository/settings/dists &</action>
        </button>
        </hbox>
        <hbox>
        <text>
				<label>REPO :</label>
			</text>
        <entry>
			<default>'$repo'</default>
			<variable>default_repo</variable>
		</entry>
		
		  <button>
        <input file>/opt/penmode/modules/repository/icons/save.png</input>
		<width>30</width>
          <action>/opt/penmode/modules/repository/settings/repo &</action>
        </button>
        </hbox>
        
        <hbox>
       <text>
				<label>ARCHS :</label>
			</text>
        <entry>
			<default>'$archs'</default>
			<variable>default_archs</variable>
		</entry>
		
		  <button>
        <input file>/opt/penmode/modules/repository/icons/save.png</input>
		<width>30</width>
          <action>/opt/penmode/modules/repository/settings/archs &</action>
        </button>
        </hbox>
        
        
        <hbox>
       <text>
				<label>COMPONENTS :</label>
			</text>
        <entry>
			<default>'$components'</default>
			<variable>default_components</variable>
		</entry>
		
		  <button>
        <input file>/opt/penmode/modules/repository/icons/save.png</input>
		<width>30</width>
          <action>/opt/penmode/modules/repository/settings/components &</action>
        </button>
        </hbox>
         
         
         <hbox>
        <button>
        <input file>/opt/penmode/icons/add.png</input>
        <width>30</width>
        <variable>FILE_BROWSE</variable>
        <action type="fileselect">path</action>
        </button>
        <entry>
        <default>'$pathrepo'</default>
        <variable>path</variable>
        </entry>
        		  <button>
        <input file>/opt/penmode/modules/repository/icons/save.png</input>
		<width>30</width>
          <action>/opt/penmode/modules/repository/settings/path &</action>
        </button>
         </hbox> 
	
        </frame>
        <frame>
        <vbox>
        <hbox>
        
        <button>
        <input file>/opt/penmode/icons/add.png</input>
        <width>30</width>
        <variable>FILE_BROWSE</variable>
        <action type="fileselect">deb</action>
        </button>
        <entry>
        <variable>deb</variable>
        </entry>
        
        <button>
        <label>ADD DEB</label>
        <action>/opt/penmode/modules/repository/settings/add &</action>
        </button>
        
        <button>
        <label>NEW REPO</label>
        <action>/opt/penmode/modules/repository/settings/crea &</action>
        </button>
        
        </hbox>
        </vbox>
        </frame>	 
	 </vbox>
</window>
'
gtkdialog --program=MAIN_DIALOG
